[project]
name = "beforerr"
version = "0.1.0"
description = "Add a short description here"
authors = [{ name = "Beforerr", email = "zzj956959688@gmail.com" }]
requires-python = ">= 3.10"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
r = ["rpy2", "rpy2_arrow"]

[tool.setuptools]
packages = ["beforerr"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
beforerr = { path = ".", editable = true }
rpy2 = "*"
rpy2-arrow = "*"
pipe = "*"

[tool.pixi.tasks]

[tool.pixi.dependencies]
nbdev = "*"
matplotlib = "*"
ipykernel = "*"
polars = "*"
# rpy2 = "*"
# r-arrow = "*"