[project]
name = "beforerr"
dynamic = ["version"]
description = "Personal Python utility library"
authors = [{ name = "Beforerr", email = "zzj956959688@gmail.com" }]
requires-python = ">= 3.10"
dependencies = ["pipe", "loguru"]
readme = "README.md"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.optional-dependencies]
r = ["rpy2", "rpy2_arrow"]

[project.urls]
Homepage = "https://beforerr.github.io/beforerr_dev"
Repository = "https://github.com/beforerr/beforerr_dev"

[tool.pdm.version]
source = "scm"
tag_filter = "test/*"
tag_regex = '^test/(?:\D*)?(?P<version>([1-9][0-9]*!)?(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*((a|b|c|rc)(0|[1-9][0-9]*))?(\.post(0|[1-9][0-9]*))?(\.dev(0|[1-9][0-9]*))?$)$'

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
beforerr = { path = ".", editable = true }
nbdev = "*"
setuptools = "*"
rpy2 = "*"
rpy2-arrow = "*"

[tool.pixi.tasks]

[tool.pixi.dependencies]
matplotlib = "*"
ipykernel = "*"
polars = "*"
# rpy2 = "*"
# r-arrow = "*"