# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/beforerr',
                'doc_host': 'https://Beforerr.github.io',
                'git_url': 'https://github.com/Beforerr/beforerr',
                'lib_path': 'beforerr'},
  'syms': { 'beforerr.basics': {'beforerr.basics.pmap': ('basics.html#pmap', 'beforerr/basics.py')},
            'beforerr.core': {'beforerr.core.foo': ('core.html#foo', 'beforerr/core.py')},
            'beforerr.matplotlib': {},
            'beforerr.polars': { 'beforerr.polars._expand_selectors': ('polars.html#_expand_selectors', 'beforerr/polars.py'),
                                 'beforerr.polars.convert_to_pd_dataframe': ('polars.html#convert_to_pd_dataframe', 'beforerr/polars.py'),
                                 'beforerr.polars.create_partitions': ('polars.html#create_partitions', 'beforerr/polars.py'),
                                 'beforerr.polars.decompose_vector': ('polars.html#decompose_vector', 'beforerr/polars.py'),
                                 'beforerr.polars.pl_norm': ('polars.html#pl_norm', 'beforerr/polars.py'),
                                 'beforerr.polars.sort': ('polars.html#sort', 'beforerr/polars.py')},
            'beforerr.r': {'beforerr.r.py2rpy_polars': ('r.html#py2rpy_polars', 'beforerr/r.py')}}}