project:
  type: website
  preview:
    port: 3000

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/Beforerr/beforerr_dev"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - nbdev.yml
