name: Deploy to GitHub Pages
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: prefix-dev/setup-pixi@v0.8.1
      - uses: fastai/workflows/quarto-ghp@master
