name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup-pixi
        uses: prefix-dev/setup-pixi@v0.8.1
      - uses: fastai/workflows/nbdev-ci@master
